# Generated by Django 4.2.4 on 2023-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(verbose_name='publish date')),
                ('duration_kms', models.FloatField(default=0)),
                ('duration_sec', models.IntegerField(default=0)),
            ],
        ),
    ]
