# Generated by Django 4.2.4 on 2023-09-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='My Epic Run!', max_length=250)),
                ('start_time', models.BigIntegerField(default=1694188033.358934)),
                ('date_pub', models.DateTimeField(verbose_name='publish date')),
                ('total_kms', models.FloatField(default=0, verbose_name='distance in kms')),
                ('total_time', models.IntegerField(default=0, verbose_name='time in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('runner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('total_kms', models.FloatField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('longest_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.run')),
            ],
        ),
        migrations.CreateModel(
            name='RunMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.run')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='runner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.runner'),
        ),
    ]
