# Generated by Django 4.2.4 on 2023-09-06 02:51

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='duration_kms',
        ),
        migrations.RemoveField(
            model_name='run',
            name='duration_sec',
        ),
        migrations.RemoveField(
            model_name='run',
            name='id',
        ),
        migrations.AddField(
            model_name='run',
            name='run_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='run',
            name='start_time',
            field=models.BigIntegerField(default=datetime.datetime(2023, 9, 6, 2, 51, 57, 687621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='run',
            name='title',
            field=models.CharField(default='My Epic Run!', max_length=250),
        ),
        migrations.AddField(
            model_name='run',
            name='total_kms',
            field=models.FloatField(default=0, verbose_name='distance in kms'),
        ),
        migrations.AddField(
            model_name='run',
            name='total_time',
            field=models.IntegerField(default=0, verbose_name='time in seconds'),
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('runner_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('total_kms', models.FloatField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('longest_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.run')),
            ],
        ),
        migrations.CreateModel(
            name='RunMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.run')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='runner_id',
            field=models.ForeignKey(default=api.models.Runner, on_delete=django.db.models.deletion.CASCADE, to='api.runner'),
        ),
    ]
