# Generated by Django 4.2.4 on 2023-09-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_run_start_time_alter_runner_longest_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='runner_firebase_uid',
            field=models.CharField(default='N/A', max_length=128),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_time',
            field=models.BigIntegerField(default=1695755101.20514),
        ),
    ]
