# Generated by Django 4.2.4 on 2023-09-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_run_duration_kms_remove_run_duration_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='start_time',
            field=models.BigIntegerField(default=1693969006.544561),
        ),
    ]
